### ISSUE TITLE
Test with WordPress v6.4 and Bellevue 2022 theme and Douglas Fir theme

### ISSUE THREAD

**Issue by taija** [BellevueCollege/mayflower-blocks#53]
Related to project BellevueCollege/website-tasks#2

**Comment by efuenzalida52** [comment]
Following bugs have been filed in regards to MFB & Bellevue College 2022 Theme:

- [Link to Issue 14](https://github.com/BellevueCollege/bellevue-2022/issues/14)
- [Link to Issue 15](https://github.com/BellevueCollege/bellevue-2022/issues/15)
- [Link to Issue 16](https://github.com/BellevueCollege/bellevue-2022/issues/16)
- [Link to Issue 17](https://github.com/BellevueCollege/bellevue-2022/issues/17)
- [Link to Issue 18](https://github.com/BellevueCollege/bellevue-2022/issues/18)
